### ISSUE TITLE
Grumblr HW

### ISSUE THREAD

**Issue by kristingreenslit** [ga-dc/grumblr_backbone#19]
Comfort: 3
Completeness: 3

Submitting an issue b/c I started from scratch vs. forking a repo. I didn't get very far b/c I had to spend time editing my portfolio site (kristingreenslit.com) in preparation for a pre-screening interview this evening. Here is the link to my repo: https://github.com/kristingreenslit/grumbler-hw/commit/2d313483a10d8ad9c5c22aecccd25bf7acda98bd?diff=unified

If you have any feedback about my portfolio site, it would be greatly appreciated!

**Comment by RobertAKARobin** [comment]
Wow! Bonus points, I guess, for starting from scratch? But not if it made everything crazy difficult!
